require('dotenv').config();

//Secure defaults
const DEFAULT_PORT = process.env.PORT || 3001;
const DEFAULT_HOST = process.env.HOST || '0.0.0.0';
let DEFAULT_SECURE = true;
let DEFAULT_HTTP_ONLY = true;
let DEFAULT_SAME_SITE = "strict";
let DEFAULT_CORS_ALLOWED_ORIGINS = ['http://localhost:3000', 'http://localhost:5173']
let ALLOW_EMPTY_ORIGIN = false;

//Initialize secrets as undefined
let DEFAULT_ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
let DEFAULT_REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET

//Apply development-specific adjustments
if (process.env.NODE_ENV === 'development') {
  DEFAULT_ACCESS_TOKEN_SECRET = DEFAULT_ACCESS_TOKEN_SECRET || "J2Adgc7PqyMT6qB+KxhlTYpyRHqp4gI7C8WDkbEVve9HJ4UFtE8DW91dg0Px1EBu";
  DEFAULT_REFRESH_TOKEN_SECRET = DEFAULT_REFRESH_TOKEN_SECRET || "sWFEpzloPT5tO4mL/jOzY5hoQd3V5I1r7uxu3faJhbilTw7WDI5pEEgPDoh2DvjS";
  DEFAULT_SECURE = false;
  DEFAULT_SAME_SITE = process.env.SAME_SITE || 'Lax';
  DEFAULT_CORS_ALLOWED_ORIGINS = process.env.CORS_ALLOWED_ORIGINS
    ? process.env.CORS_ALLOWED_ORIGINS.split(',')
    : DEFAULT_CORS_ALLOWED_ORIGINS;
  ALLOW_EMPTY_ORIGIN = true;
}

//Enforce secrets presence
if (!DEFAULT_ACCESS_TOKEN_SECRET || !DEFAULT_REFRESH_TOKEN_SECRET) {
  throw new Error("ACCESS_TOKEN_SECRET and REFRESH_TOKEN_SECRET must be set in all enviroments.");
}

//Final constants for export
const ACCESS_TOKEN_SECRET = DEFAULT_ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = DEFAULT_REFRESH_TOKEN_SECRET;
const PORT = DEFAULT_PORT;
const HOST = DEFAULT_HOST;
const SECURE = DEFAULT_SECURE;
const HTTP_ONLY = DEFAULT_HTTP_ONLY;
const SAME_SITE_TYPES = { STRICT: "Strict", LAX: "Lax", NONE: "None" };
const SAME_SITE = SAME_SITE_TYPES[DEFAULT_SAME_SITE.toUpperCase()] || SAME_SITE_TYPES.STRICT;
const CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ALLOWED_ORIGINS;

//Add DB and ReCAPTCHA
const DB_CONNECTION_STRING = process.env.DB_CONNECTION_STRING;
const SECRET_RECAPTCHA_SERVER_KEY = process.env.SECRET_RECAPTCHA_SERVER_KEY;

//Validate DB and ReCAPTCHA
if (!DB_CONNECTION_STRING) throw new Error("DB_CONNECTION_STRING must be set.");
if (!SECRET_RECAPTCHA_SERVER_KEY) throw new Error("SECRET_RECAPTCHA_SERVER_KEY must be set.");

module.exports = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  PORT,
  HOST,
  SECURE,
  HTTP_ONLY,
  SAME_SITE,
  SAME_SITE_TYPES,
  CORS_ALLOWED_ORIGINS,
  ALLOW_EMPTY_ORIGIN,
  DB_CONNECTION_STRING,
  SECRET_RECAPTCHA_SERVER_KEY
}